import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'styles/Home.module.scss'
import Card from 'components/Card'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Plovdiv Events</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Card />
      </main>
    </div>
  )
}

export default Home
